spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/test # 4000 for fedora, 5432 for windows
        driver-class-name: org.postgresql.Driver
        username: user
        password: pass

server:
    port: 3000
    servlet:
        context-path: /v1/food-api

food:
    user-paths:
        - "/recipe/delete"
        - "/recipe"
        - "/recipe/addFavorite"
        - "/savedRecipes/delete"